spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_data?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=TRUE
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

app-config:
  maxClassAllowed: 10

springdoc:
  usemanagementport: true

server:
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui,health,info