spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_data?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=TRUE
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # Hibernate is disabled because Liquibase will manage schema
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app-config:
  maxClassAllowed: 10

springdoc:
  use-management-port: true
  swagger-ui:
    enabled: true

server:
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,openapi,swagger-ui
